spring:
  datasource:
    url: ${DATASOURCE_NAME:jdbc:h2:mem:user}
    username: ${DATASOURCE_USER:sa}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  jpa:
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": true
      "[org.hibernate.envers.audit_table_suffix]": _log
    database-platform: ${DATASOURCE_DIALECT:org.hibernate.dialect.H2Dialect}
    show-sql: true
  liquibase:
    enabled: true
    url: ${DATASOURCE_URL:jdbc:h2:mem:user}
    user: ${DATASOURCE_USER:sa}
    password: ${DATASOURCE_PASSWORD:}
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": ERROR
    "[org.martikan.mastore]": DEBUG
    "[org.hibernate]": DEBUG