spring:
  datasource:
    url: jdbc:h2:mem:usersTest
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": ERROR
    "[org.martikan.mastore]": DEBUG
    "[org.hibernate]": DEBUG