server:
  port: ${PORT:0}

spring:
  application:
    name: users-ws
  datasource:
    url: ${DATASOURCE_NAME}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    database-platform: ${DATASOURCE_DIALECT}
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  liquibase:
    enabled: true
    url: ${DATASOURCE_URL}
    user: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  instance:
    instance-id: ${spring.application.name}:${APPLICATION_INSTANCE_ID:${random.uuid}}
  client:
    service-url:
      default-zone: ${EUREKA_DEFAULT_ZONE}

management:
  endpoint:
    shutdown:
      enabled: true