spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/users?serverTimezone=CET&max_allowed_packet=15728640}
    username: ${DATASOURCE_USER:users}
    password: ${DATASOURCE_PASSWORD:aaa}
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.generate_statistics]": true
      "[org.hibernate.envers.audit_table_suffix]": _log
    database-platform: ${DATASOURCE_DIALECT:org.hibernate.dialect.MySQL5InnoDBDialect}
    show-sql: true
  liquibase:
    enabled: true
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/users?serverTimezone=CET&max_allowed_packet=15728640}
    user: ${DATASOURCE_USER:users}
    password: ${DATASOURCE_PASSWORD:aaa}
    change-log: classpath:db/changelog/changelog-master.xml
  h2:
    console:
      enabled: true
      path: /h2
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761}

management:
  endpoints:
    web:
      exposure:
        include: '*'

token:
  expiration: ${TOKEN_EXPIRATION:864000000} # 10 days by default
  secret: ${TOKEN_SECRET:asdWasdWASGHEt31Sh34As5}

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    "[org.springframework.web]": ERROR
    "[org.martikan.mastore]": DEBUG
    "[org.hibernate]": DEBUG

server:
  port: ${PORT:8085}